repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.67.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
