name: "Validate"

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
